### ISSUE TITLE
scrollbar 

### ISSUE THREAD

**Issue by etunadev** [etuna86/find-your-dudes-v1#1]
tasarımdaki scrollbar ları ekledim ama  blockların  sağ taraflarında  boşluk  oluştu  buna bir çözüm bulamadım. Ona  bakacağım.

**Comment by crmsoft** [comment]
sanirsam ozel bir scrollbara ihtiyacimiz yok, tasarimdan hatirlamiyorun bir daha bakarim ama
https://github.com/etuna86/find-your-dudes-v1/blob/fb304a4825383e1fa1831ec3f8725b96a3920264/src/scss/find-your-dudes.scss#L38

burdaki scroll "auto" olmali  bence, bi de .my-games scroll olmali .col-md-3 degil

**Comment by etunadev** [comment]
düzenlemeri  yaptım   .col-md lerde n scroları  çıkardım    .my-games scroll   kısımlarına ekledim  owerflow hidden yaptım  duruma göre scrol açarız
